on:
  schedule:
    - cron:  '30 6 * * *'
  push:
    branches:
      - master

env:
  B2_KEY_ID: "001a56c121eaece0000000009"
  B2_BUCKET: "dl-estate"
  B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
  MAPQUEST_API_KEY: ${{ secrets.MAPQUEST_API_KEY }}
  GH_GIST_ID: "51ce817d1bca483b3bd0532b8e00233c"
  GH_API_KEY: ${{ secrets.GH_API_KEY }}

jobs:
  scrape:
    runs-on: ubuntu-16.04
    name: Analyze and publish results
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip setuptools wheel
        shell: bash
      - name: Check Python version
        run: python3 --version && python3 -m pip --version && pip list
        shell: bash
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup virtualenv and install dependencies
        run: make setup
        shell: bash
      - name: Cache scraped offers
        uses: actions/cache@v2
        with:
          path: ./bucket
          key: b2-bucket
      - name: Download scraped offer data from B2
        run: make dl-data
        shell: bash
      - name: Perform analysis
        run: make analyze
        shell: bash
      - name: Render GeoJSON map and publish as gist
        run: make render publish
        shell: bash
      - name: Publish rendered map as gist
        run: make render publish
        shell: bash